SEARCH_DIR(.\)
SEARCH_DIR(c:\dev-pas\units\)
SEARCH_DIR(c:\dev-pas\units\rtl\)
INPUT(
c:\dev-pas\units\rtl\wprt0.ow
\\athena.root\students\667001\cs1\ftoc\finished\quevbp03.ow
)
GROUP(
c:\dev-pas\units\rtl\LIBPWI~2.AW
c:\dev-pas\units\rtl\LIBPST~1.AW
c:\dev-pas\units\rtl\libpdos.aw
c:\dev-pas\units\rtl\libpcrt.aw
c:\dev-pas\units\rtl\LIBPOB~2.AW
c:\dev-pas\units\rtl\LIBPSY~2.AW
)
